name: Formatting check
on:
- pull_request

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Black Code Formatter
      uses: lgeiger/black-action@master
      with:
        args: "-l 100 pennylane_honeywell/ --check"
